# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: "3.7"
services:
  # Webapp
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "18001:5000"
    volumes:
      - ./sources:/usr/src/app/sources
      - ./extracted:/usr/src/app/extracted
